name: Poisoned Pages
favicon: null
layout_spectrum: 0.5338377086445689
typography_spectrum: 0.1530236208345741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9474a'
    - '#000000'
    - '#ff0000'
    - '#800000'
    - '#993333'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
